"""initial schema

Revision ID: 3ca53ae0e834
Revises: 
Create Date: 2026-05-27 08:44:52.106487
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ca53ae0e834'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_status'), 'exams', ['status'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cccd', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_cccd'), 'candidates', ['cccd'], unique=True)
    op.create_index(op.f('ix_candidates_exam_id'), 'candidates', ['exam_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_table('exam_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('option_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='waiting', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_correct', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sessions_candidate_id'), 'exam_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_exam_id'), 'exam_sessions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_status'), 'exam_sessions', ['status'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_answer_session_question')
    )
    op.create_index(op.f('ix_answers_session_id'), 'answers', ['session_id'], unique=False)
    op.create_table('exam_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('cccd_attempted', sa.String(length=12), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_events_cccd_attempted'), 'exam_events', ['cccd_attempted'], unique=False)
    op.create_index(op.f('ix_exam_events_created_at'), 'exam_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_exam_events_event_type'), 'exam_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_exam_events_session_id'), 'exam_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_events_session_id'), table_name='exam_events')
    op.drop_index(op.f('ix_exam_events_event_type'), table_name='exam_events')
    op.drop_index(op.f('ix_exam_events_created_at'), table_name='exam_events')
    op.drop_index(op.f('ix_exam_events_cccd_attempted'), table_name='exam_events')
    op.drop_table('exam_events')
    op.drop_index(op.f('ix_answers_session_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_exam_sessions_status'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_exam_id'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_candidate_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_candidates_exam_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_cccd'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_exams_status'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
