"""Provision load-test data: 1 active exam + 1 active sitting, N candidates,
N in_progress sessions.

Run inside the backend container:
    python load_tests/setup_load.py           # provision N=1000 (default)
    N=500 python load_tests/setup_load.py     # override N
    python load_tests/setup_load.py cleanup   # remove LOAD TEST data

CRITICAL: The load exam is ACTIVE → a leftover exam blocks creating real exams
(at-most-1-active invariant, AD-47). Always run cleanup when done!
"""

import asyncio
import json
import os
import sys
import uuid
from datetime import date, datetime, timedelta, timezone

from sqlalchemy import delete, select

from app.core.redis import redis_client
from app.database import AsyncSessionLocal
from app.models import Candidate, Exam, ExamSession, Sitting
from app.models.enums import ExamStatus, SessionStatus, SittingStatus
from app.services import session_service

# Parametrize via env var or argv
try:
    N = int(os.environ.get("N", "1000"))
except ValueError:
    N = 1000

NUM_Q = 30  # số câu hỏi trong payload Redis
EXAM_NAME = "LOAD TEST"


def _build_payload(num_q: int) -> dict:
    """Build a realistic payload dict (no images) for num_q questions."""
    questions = []
    for i in range(num_q):
        qid = str(uuid.uuid4())
        questions.append({
            "id": qid,
            "text": f"Câu hỏi tải số {i + 1}: Đây là câu hỏi kiểm tra tải hệ thống?",
            "images": [],
            "options": [
                {"id": o, "text": f"Đáp án {o} của câu {i + 1}", "images": []}
                for o in ["A", "B", "C", "D"]
            ],
            "correct_option": "ABCD"[i % 4],
            "order_index": i,
        })
    return {"questions": questions}


async def cleanup(db=None) -> None:
    """Remove ALL data from the LOAD TEST exam (sessions, candidates, sitting, exam,
    Redis payload). Idempotent — safe to call even when there is no load test exam."""
    close_db = db is None
    if db is None:
        db = AsyncSessionLocal()
        await db.__aenter__()
    try:
        old_exam = await db.scalar(select(Exam).where(Exam.name == EXAM_NAME))
        if old_exam is None:
            print("No LOAD TEST exam found — nothing to clean up.")
            return
        exam_id = old_exam.id

        # Get all sittings so we can delete their Redis payload keys.
        sittings = list(await db.scalars(select(Sitting).where(Sitting.exam_id == exam_id)))
        sitting_ids = [s.id for s in sittings]

        # Delete in FK order: answers → sessions → candidates → sittings → exam.
        session_ids = list(await db.scalars(
            select(ExamSession.id).where(ExamSession.exam_id == exam_id)
        ))
        if session_ids:
            from app.models.answer import Answer  # noqa: PLC0415
            await db.execute(delete(Answer).where(Answer.session_id.in_(session_ids)))
        await db.execute(delete(ExamSession).where(ExamSession.exam_id == exam_id))
        await db.execute(delete(Candidate).where(Candidate.exam_id == exam_id))
        await db.execute(delete(Sitting).where(Sitting.exam_id == exam_id))
        await db.delete(old_exam)
        await db.commit()

        # Redis payload + report cache per sitting.
        for sid in sitting_ids:
            await redis_client.delete(session_service.payload_key(sid))
            await redis_client.delete(session_service.report_cache_key(sid))
        # Also clear the active-exams cache so the new state is picked up immediately.
        await redis_client.delete(session_service._ACTIVE_EXAMS_CACHE_KEY)

        print(f"Cleanup done: removed exam {exam_id} + {len(sittings)} sitting(s).")
    finally:
        if close_db:
            await db.__aexit__(None, None, None)


async def setup() -> None:
    async with AsyncSessionLocal() as db:
        # --- Idempotent: remove any previous LOAD TEST run first ---
        old_exam = await db.scalar(select(Exam).where(Exam.name == EXAM_NAME))
        if old_exam is not None:
            print(f"Found previous LOAD TEST exam {old_exam.id} — cleaning up first …")
            await cleanup(db)

        # --- Exam (kỳ thi) ---
        exam = Exam(
            name=EXAM_NAME,
            description="Auto-generated by setup_load.py",
            duration_minutes=120,
            exam_date=date.today(),
            status=ExamStatus.ACTIVE.value,
            allow_registration=False,
        )
        db.add(exam)
        await db.flush()

        # --- Build Redis payload ---
        payload = _build_payload(NUM_Q)
        qids = [q["id"] for q in payload["questions"]]
        opt_order = {qid: ["A", "B", "C", "D"] for qid in qids}

        # --- Sitting (buổi thi) ---
        sitting = Sitting(
            exam_id=exam.id,
            name="Buổi tải thử",
            ordinal=1,
            duration_minutes=120,
            status=SittingStatus.ACTIVE.value,
            shuffle_questions=False,
            shuffle_options=False,
            question_count=NUM_Q,
            encrypted_payload=b"load_test_placeholder",
            report_snapshot=[
                {
                    "id": q["id"],
                    "text": q["text"],
                    "correct_option": q["correct_option"],
                }
                for q in payload["questions"]
            ],
        )
        db.add(sitting)
        await db.flush()

        # Push payload into Redis (TTL = duration + 30 min buffer).
        redis_key = session_service.payload_key(sitting.id)
        await redis_client.set(
            redis_key,
            json.dumps(payload, ensure_ascii=False),
            ex=sitting.duration_minutes * 60 + 1800,
        )
        # Invalidate active-exams cache so endpoints see the new exam immediately.
        await redis_client.delete(session_service._ACTIVE_EXAMS_CACHE_KEY)

        # --- N candidates ---
        now = datetime.now(timezone.utc)
        end = now + timedelta(hours=2)

        candidates = []
        for i in range(1, N + 1):
            candidates.append(Candidate(
                cccd=f"8{i:011d}",
                id_type="cccd",
                full_name=f"Thí sinh tải {i}",
                birth_date=date(2000, 1, 1),
                unit="ĐV Tải",
                category="Đối tượng 1",
                attempt_number=1,
                exam_id=exam.id,
            ))
        db.add_all(candidates)
        await db.flush()

        # --- N in_progress sessions (one per candidate in this sitting) ---
        sessions = [
            ExamSession(
                candidate_id=c.id,
                exam_id=exam.id,
                sitting_id=sitting.id,
                status=SessionStatus.IN_PROGRESS.value,
                question_order=qids,
                option_order=opt_order,
                started_at=now,
                end_time=end,
            )
            for c in candidates
        ]
        db.add_all(sessions)
        await db.commit()

        print(
            f"Load setup done: exam_id={exam.id}, sitting_id={sitting.id}, "
            f"{N} candidates + in_progress sessions, {NUM_Q} questions."
        )
        print(f"Redis key: {redis_key}")
        print(f"⚠  Remember to run: python load_tests/setup_load.py cleanup   (MANDATORY after test)")


def teardown() -> None:
    """Convenience sync wrapper for external callers."""
    asyncio.run(cleanup())


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "cleanup":
        asyncio.run(cleanup())
    else:
        asyncio.run(setup())
